---
abstract: 'Attribute wrappers for CPAN Tie classes'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attribute-TieClasses
provides:
  Attribute::TieClasses:
    file: lib/Attribute/TieClasses.pm
    version: 1.101700
requires:
  Attribute::Handlers: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Attribute-TieClasses
  homepage: http://search.cpan.org/dist/Attribute-TieClasses/
  repository: http://github.com/hanekomu/Attribute-TieClasses
version: 1.101700
